config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'groups#index'
  resources :users, only: [:index, :edit, :update]
  resources :groups, only: [:index, :new, :create, :edit, :update] do
    resources :messages, only: [:index, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users
  has_many :messages
  validates :name, presence: true
  accepts_nested_attributes_for :group_users

  attr_accessor :keyword 
  def show_last_message
    if (last_message = messages.last).present?
      last_message.content? ? last_message.content : '画像が投稿されています'
    else
      'メッセージがありません'
    end
  end
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group, inverse_of: :group_users, optional: true
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :group
  belongs_to :user

  validates :content, presence: true, unless: :image?
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :messages
  has_many :group_users
  has_many :groups, through: :group_users
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:edit, :update]

  def index
    @groups = Group.all
  end

  def new
    @group = Group.new
    @group.users << current_user
  end

  def create
    @group = Group.create(group_params)
    if @group.save
      redirect_to root_path, notice: "グループの作成に成功しました。"
    else
      render :new
    end
  end

  def edit 
  end

  def update 
    if @group.update(group_params)
      redirect_to root_path, notice: "グループの編集に成功しました。"
    else
      render :edit
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, { :user_ids => [] })
  end

  def set_group
    @group = Group.find(params[:id])
  end 
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_group, only: [:index, :create]

  def index
    @messages = @group.messages.includes(:user)
    @message = Message.new
    respond_to do |format|
      format.html
      format.json { @last_messages = Message.where('id > ?', params[:id]) }
    end
  end

  def create
    @message = Message.new(message_params)
    if @message.save
      respond_to do |format|
        format.json
      end
    else
      @messages = @group.messages.includes(:user)
      flash.now[:alert] = 'メッセージを入力してください。'
      render :index
    end
  end

  private

  def message_params
    params.require(:message).permit(:content, :image, :user_id).merge(group_id: params[:group_id])
  end

  def set_group
    @group = Group.find(params[:group_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    if params[:keyword].present?
      @users = User.where('name LIKE(?)', "%#{params[:keyword]}%").where.not(id: current_user.id)
    else
      @users = []
    end
    respond_to do |format|
      format.json
    end
  end

  def edit 
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end 
  end

  private
  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = render partial: "shared/form", locals: {group: @group} 

app/views/groups/index.html.haml
.contents
  = render partial: "shared/side_bar" 

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = render partial: "shared/form", locals: {group: @group} 

app/views/layouts/_notifications.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ChatSpace2
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/notifications'
    = yield

app/views/messages/index.html.haml
.contents
  = render partial: "shared/side_bar"
  .messagesbox
    .messagesbox__header
      .messagesbox__header__title
        %span{class: 'group-name', id: "#{@group.id}"} グループ名：
        = @group.name
      .messagesbox__header__members
        %span メンバー：
        - @group.users.each do |user|
          = user.name
      .messagesbox__header__button
        = link_to "編集", edit_group_path(@group)
    .messagesbox__body
      = render partial: "shared/message", collection: @messages, as: :message
    .messagesbox__footer
      .messagesbox__fotter__form
        = form_for [@group, @message] do |f|
          = f.hidden_field :user_id, value: current_user.id
          = f.text_field :content
          = f.submit "ボタン", class: "button"
          = f.file_field :image, class: "image"

app/views/shared/_form.html.haml
= form_for group do |f|
  - if group.errors.any?
    .chat-group-form__errors
      %h2= "#{group.errors.full_messages.count}件のエラーが発生しました。"
      %ul
        - group.errors.full_messages.each do |message|
          %li= message
  / グループ名の入力欄
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label :name, class: 'chat-group-form__label'
    .chat-group-form__field--right
      = f.text_field :name, class: 'chat__group_name chat-group-form__input', placeholder: 'グループ名を入力してください'
      = f.collection_check_boxes :user_ids, User.all, :id, :name, include_hidden: false do |b|
        = b.check_box(class: 'bbbb')
        = b.label(class: 'abcd')
  / ユーザー名の検索入力欄
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label 'チャットメンバーを追加', class: 'chat-group-form__label'
    .chat-group-form__field--right
      .chat-group-form__field__search.clearfix
        /%input#user-search-field.chat-group-form__input{type: "text", placeholder: '追加したいユーザーを入力してください'}
        = f.text_field :keyword, id: 'user-search-field', class: 'chat-group-form__input', placeholder: '追加したいユーザーを入力してください'
      #user-search-result
  / ユーザー一覧
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label 'チャットメンバー', class: 'chat-group-form__label'
    .chat-group-form__field--right
      .chat-group-users
        %div{class: 'chat-group-user clearfix', id: current_user.id}
          %input#group_user_ids{name: 'group[user_ids][]', type: 'hidden', value: current_user.id}
          %p= current_user.name
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
    .chat-group-form__field--right
      = f.submit class: 'chat-group-form__action-btn'

app/views/shared/_message.html.haml
.message{"data-message-id" => "#{message.id}"}
  %span.message__name
    = message.user.name
  %span.message__time
    = message.created_at.strftime("%-m/%-d %-H:%-M")
  .message__content
    = message.content
  .message__image
    = image_tag message.image.url, class: "image" if message.image.present?

app/views/shared/_side_bar.html.haml
.side-bar
  .header
    %h3.header__name
      = current_user.name
    %ul.header__lists
      %li.list
        = link_to new_group_path do
          = fa_icon 'pencil-square-o', class: 'icon'
      %li.list
        = link_to edit_user_path(current_user) do
          = fa_icon 'cog', class: 'icon'
  .groups
    - current_user.groups.each do |group|
      .group
        .group__name
          = link_to "#{group.name}", group_messages_path(group)
        %span.group__message
          = group.show_last_message 

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'